Cards = {
    '': 0,
    'Ace of Diamonds': 11,
    'Two of Diamonds': 2,
    'Three of Diamonds': 3,
    'Four of Diamonds': 4,
    'Five of Diamonds': 5,
    'Six of Diamonds': 6,
    'Seven of Diamonds': 7,
    'Eight of Diamonds': 8,
    'Nine of Diamonds': 9,
    'Ten of Diamonds': 10,
    'Jack of Diamonds': 10,
    'Queen of Diamonds': 10,
    'King of Diamonds': 10,
    'Ace of Clubs': 11,
    'Two of Clubs': 2,
    'Three of Clubs': 3,
    'Four of Clubs': 4,
    'Five of Clubs': 5,
    'Six of Clubs': 6,
    'Seven of Clubs': 7,
    'Eight of Clubs': 8,
    'Nine of Clubs': 9,
    'Ten of Clubs': 10,
    'Jack of Clubs': 10,
    'Queen of Clubs': 10,
    'King of Clubs': 10,
    'Ace of Hearts': 11,
    'Two of Hearts': 2,
    'Three of Hearts': 3,
    'Four of Hearts': 4,
    'Five of Hearts': 5,
    'Six of Hearts': 6,
    'Seven of Hearts': 7,
    'Eight of Hearts': 8,
    'Nine of Hearts': 9,
    'Ten of Hearts': 10,
    'Jack of Hearts': 10,
    'Queen of Hearts': 10,
    'King of Hearts': 10,
    'Ace of Spades': 11,
    'Two of Spades': 2,
    'Three of Spades': 3,
    'Four of Spades': 4,
    'Five of Spades': 5,
    'Six of Spades': 6,
    'Seven of Spades': 7,
    'Eight of Spades': 8,
    'Nine of Spades': 9,
    'Ten of Spades': 10,
    'Jack of Spades': 10,
    'Queen of Spades': 10,
    'King of Spades': 10
}

Card_Names = [
    '',
    'Ace of Diamonds',
    'Two of Diamonds',
    'Three of Diamonds',
    'Four of Diamonds',
    'Five of Diamonds',
    'Six of Diamonds',
    'Seven of Diamonds',
    'Eight of Diamonds',
    'Nine of Diamonds',
    'Ten of Diamonds',
    'Jack of Diamonds',
    'Queen of Diamonds',
    'King of Diamonds',
    'Ace of Clubs',
    'Two of Clubs',
    'Three of Clubs',
    'Four of Clubs',
    'Five of Clubs',
    'Six of Clubs',
    'Seven of Clubs',
    'Eight of Clubs',
    'Nine of Clubs',
    'Ten of Clubs',
    'Jack of Clubs',
    'Queen of Clubs',
    'King of Clubs',
    'Ace of Hearts',
    'Two of Hearts',
    'Three of Hearts',
    'Four of Hearts',
    'Five of Hearts',
    'Six of Hearts',
    'Seven of Hearts',
    'Eight of Hearts',
    'Nine of Hearts',
    'Ten of Hearts',
    'Jack of Hearts',
    'Queen of Hearts',
    'King of Hearts',
    'Ace of Spades',
    'Two of Spades',
    'Three of Spades',
    'Four of Spades',
    'Five of Spades',
    'Six of Spades',
    'Seven of Spades',
    'Eight of Spades',
    'Nine of Spades',
    'Ten of Spades',
    'Jack of Spades',
    'Queen of Spades',
    'King of Spades'
]

Availables = []
for x in range(1, 53):
    Availables.append(x)
